#!/usr/bin/env python3
"""Check every docs page appears in `docs/sidebars.ts`.

The sidebar used to be `{type: 'autogenerated', dirName: '.'}`, which
covered every page by construction. It is now an explicit tree, so the
sidebar became a registration surface: a page added without an entry is
reachable by URL but absent from navigation, in this repo and in
`opsmill/infrahub-docs`, which is handed the same file by
`.github/workflows/sync-docs.yml`.

Docusaurus only warns about this, and the warning does not fail
`npm run build`. So this runs as a linter instead.

The parse is textual rather than a TypeScript evaluation, matching
`scripts/check-cli-invocations.py`. The sidebar is a literal, so quoted
strings and `dirName:` values are all that has to be read.

Usage::

    python scripts/check-docs-sidebar.py
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = ROOT / "docs" / "docs"
SIDEBAR = ROOT / "docs" / "sidebars.ts"

DOC_SUFFIXES = {".md", ".mdx"}

# A `//` comment can say anything, including a page's own id, without
# registering it as covered — this file's own header comment once mentioned
# 'skills' in a sentence and shadowed a hypothetical skills.mdx.
_COMMENT_LINE = re.compile(r"^\s*//.*$", re.MULTILINE)

# A string counts as a doc ID only in an ID position: a bare array element
# ('readme', 'skills-reference/...') or the value of an `id:` key (a
# category's `link: {type: 'doc', id: '...'}`). Every other quoted string —
# a label, a title, a slug, a `type:` value — sits after some other
# property name and a colon, which is how `doc.mdx` and `category.mdx`
# used to pass while unlisted: `type: 'doc'` and the literal `'category'`
# read as coverage for pages with those ids.
_ID_ELEMENT = re.compile(r"""[\[,]\s*['"]([^'"\n]+)['"]""")
_ID_VALUE = re.compile(r"""\bid\s*:\s*['"]([^'"\n]+)['"]""")
_DIRNAME = re.compile(r"""dirName\s*:\s*['"]([^'"\n]+)['"]""")


def doc_ids(docs_dir: Path) -> set[str]:
    """Every doc ID under `docs_dir`: the POSIX path, minus the suffix."""
    ids: set[str] = set()
    for path in docs_dir.rglob("*"):
        if path.is_file() and path.suffix in DOC_SUFFIXES:
            ids.add(path.relative_to(docs_dir).with_suffix("").as_posix())
    return ids


def covered_ids(sidebar_text: str, all_ids: set[str]) -> set[str]:
    """The subset of `all_ids` the sidebar text accounts for.

    Comment lines are stripped first, so a sentence explaining the file
    cannot accidentally register a page as covered. Two coverage forms
    remain: an ID in an ID position (an array element or an `id:` value),
    or an `autogenerated` entry whose `dirName` is the ID's ancestor (`.`
    being every page).
    """
    text = _COMMENT_LINE.sub("", sidebar_text)
    quoted = set(_ID_ELEMENT.findall(text)) | set(_ID_VALUE.findall(text))
    dirnames = set(_DIRNAME.findall(text))

    covered = {doc_id for doc_id in all_ids if doc_id in quoted}

    for dirname in dirnames:
        prefix = "" if dirname in {".", "./"} else dirname.strip("/") + "/"
        covered |= {doc_id for doc_id in all_ids if doc_id.startswith(prefix)}

    return covered


def main() -> int:
    if not SIDEBAR.is_file():
        print(f"FAIL: {SIDEBAR.relative_to(ROOT)} not found.")
        return 1

    all_ids = doc_ids(DOCS_DIR)
    if not all_ids:
        print(f"FAIL: no docs pages found under {DOCS_DIR.relative_to(ROOT)}.")
        return 1

    missing = sorted(all_ids - covered_ids(SIDEBAR.read_text(encoding="utf-8"), all_ids))
    if not missing:
        print(f"OK: all {len(all_ids)} docs pages appear in docs/sidebars.ts.")
        return 0

    print(f"FAIL: {len(missing)} docs page(s) missing from docs/sidebars.ts.\n")
    for doc_id in missing:
        print(f"  {doc_id}")
    print(
        "\nAdd each ID to the right category in docs/sidebars.ts. A page "
        "absent from the sidebar is reachable by URL but invisible in "
        "navigation, here and in opsmill/infrahub-docs."
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
