import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This sidebar is synced verbatim to opsmill/infrahub-docs as
// `sidebars-ai-skills.ts` by .github/workflows/sync-docs.yml, where the
// docs-ai-skills plugin mounts docs-ai-skills/ at routeBasePath 'skills'.
//
// The exported key must stay `AISkillsSidebar`. That repo's navbar binds to it
// by name, and nothing in this repo would catch a rename.
//
// Neither collapsed nor collapsible is set anywhere here. Both sites that
// render this file decide that themselves, and infrahub-docs sets
// sidebarCollapsed on its plugin instance. This matches infrahub-demo-otn.
//
// Document ids are bare rather than prefixed with the section name, because
// the prefix comes from the mount point there and from routeBasePath '/' here.
// A prefix in the ids would resolve in neither place.
//
// The order is the order a reader meets the product. Start here carries the
// four pages a newcomer needs before anything else, ending with how the
// skills load and the Concept Tutor, the on-ramp for someone with no
// Infrahub background. Spec-Driven Development comes right after: it is a
// mode of working with every skill that follows, not a topic of its own.
// Build your model, Automate and Load data in follow the lifecycle: define the
// shape, automate against it, then get real data in. Operate and inspect is
// for a running instance, and When something breaks is the escalation path,
// ordered collect, analyze, report. Contribute is last before the release
// notes because it addresses a different audience.
//
// Release Notes is an explicit category so it keeps its generated-index
// landing page. Its items stay autogenerated, so a new release note needs no
// edit to this file.
const sidebars: SidebarsConfig = {
  AISkillsSidebar: [
    'readme',
    {
      type: 'category',
      label: 'Start here',
      items: [
        'installation-setup',
        'first-schema',
        'choosing-a-skill',
        'how-it-works',
        'skills-reference/teaching-concepts',
      ],
    },
    {
      type: 'category',
      label: 'Spec-Driven Development',
      link: {type: 'doc', id: 'spec-driven-development'},
      items: [
        'spec-kit-integration',
        'sdd-walkthrough-vlan',
      ],
    },
    {
      type: 'category',
      label: 'Build your model',
      items: [
        'skills-reference/managing-schemas',
        'skills-reference/managing-objects',
        'skills-reference/managing-menus',
      ],
    },
    {
      type: 'category',
      label: 'Automate',
      items: [
        'skills-reference/managing-generators',
        'skills-reference/managing-transforms',
        'skills-reference/managing-checks',
      ],
    },
    {
      type: 'category',
      label: 'Load data in',
      items: [
        'skills-reference/importing-data',
        'skills-reference/converting-netbox-device-types',
      ],
    },
    {
      type: 'category',
      label: 'Operate and inspect',
      items: [
        'skills-reference/analyzing-data',
        'skills-reference/auditing-repo',
        'skills-reference/planning-upgrades',
      ],
    },
    {
      type: 'category',
      label: 'When something breaks',
      items: [
        'skills-reference/collecting-diagnostics',
        'skills-reference/analyzing-diagnostics',
        'skills-reference/reporting-issues',
        'skills-reference/reporting-skill-gaps',
      ],
    },
    {
      type: 'category',
      label: 'Contribute',
      items: [
        'contributing/anatomy-of-a-skill',
        'contributing/skill-change-pipeline',
      ],
    },
    {
      type: 'category',
      label: 'Release Notes',
      link: {
        type: 'generated-index',
        title: 'Release Notes',
        slug: '/release-notes',
        description:
          'What changed in each release of Infrahub Skills, and what is different about your workflow after upgrading. Newest first.',
      },
      items: [{type: 'autogenerated', dirName: 'release-notes'}],
    },
  ],
};

export default sidebars;
