---
name: Release drafter

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

permissions:
  contents: write
  pull-requests: read

jobs:
  update-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GH_INFRAHUB_BOT_TOKEN }}
