"""Tests for scripts/check-docs-sidebar.py.

An explicit sidebar is a registration surface: a page added without an
entry vanishes from navigation and Docusaurus only warns. These tests pin
the two coverage forms the sidebar can use (an explicit id, an
autogenerated subtree) so the script cannot quietly stop catching a gap.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
_SCRIPT = ROOT / "scripts" / "check-docs-sidebar.py"
_spec = importlib.util.spec_from_file_location("check_docs_sidebar", _SCRIPT)
check_docs_sidebar = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(check_docs_sidebar)

doc_ids = check_docs_sidebar.doc_ids
covered_ids = check_docs_sidebar.covered_ids


def _write(root: Path, rel: str, body: str = "# x\n") -> None:
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")


def test_doc_ids_strips_extension_and_is_relative(tmp_path: Path) -> None:
    _write(tmp_path, "readme.mdx")
    _write(tmp_path, "skills-reference/managing-schemas.mdx")
    _write(tmp_path, "release-notes/release-1_2_8.mdx")
    assert doc_ids(tmp_path) == {
        "readme",
        "skills-reference/managing-schemas",
        "release-notes/release-1_2_8",
    }


def test_doc_ids_ignores_non_markdown(tmp_path: Path) -> None:
    _write(tmp_path, "readme.mdx")
    _write(tmp_path, "skills-reference/_category_.json", "{}\n")
    assert doc_ids(tmp_path) == {"readme"}


def test_explicit_id_is_covered() -> None:
    sidebar = "const sidebars = { AISkillsSidebar: ['readme'] };"
    assert covered_ids(sidebar, {"readme"}) == {"readme"}


def test_autogenerated_root_covers_everything() -> None:
    sidebar = "{ type: 'autogenerated', dirName: '.' }"
    all_ids = {"readme", "skills-reference/managing-schemas"}
    assert covered_ids(sidebar, all_ids) == all_ids


def test_autogenerated_subtree_covers_only_its_prefix() -> None:
    sidebar = "{ type: 'autogenerated', dirName: 'release-notes' }"
    all_ids = {"readme", "release-notes/release-1_2_8"}
    assert covered_ids(sidebar, all_ids) == {"release-notes/release-1_2_8"}


def test_missing_id_is_not_covered() -> None:
    """The defect this script exists to catch."""
    sidebar = "const sidebars = { AISkillsSidebar: ['readme'] };"
    all_ids = {"readme", "contributing/anatomy-of-a-skill"}
    assert covered_ids(sidebar, all_ids) == {"readme"}


def test_a_substring_of_a_listed_id_is_not_covered() -> None:
    """A near miss: 'readme' appearing in the file must not cover
    'contributing/readme-extra'."""
    sidebar = "const sidebars = { AISkillsSidebar: ['readme'] };"
    all_ids = {"readme", "contributing/readme-extra"}
    assert covered_ids(sidebar, all_ids) == {"readme"}


def test_real_repo_sidebar_covers_every_real_page() -> None:
    """The live check, as CI runs it."""
    docs_dir = ROOT / "docs" / "docs"
    sidebar = (ROOT / "docs" / "sidebars.ts").read_text(encoding="utf-8")
    all_ids = doc_ids(docs_dir)
    assert all_ids, "no docs pages found"
    assert covered_ids(sidebar, all_ids) == all_ids
